# Generated by Django 5.2.6 on 2025-09-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about your sustainability journey', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='co2_saved',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total CO2 saved in kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='eco_level',
            field=models.CharField(choices=[('apprentice', 'Eco Apprentice'), ('ninja', 'Eco Ninja'), ('legend', 'Eco Legend')], default='apprentice', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='eco_points',
            field=models.PositiveIntegerField(default=0, help_text='Points earned through sustainable actions'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', help_text='Preferred language code', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.PositiveIntegerField(default=50, help_text='Trust score based on user behavior (0-100)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
