# Generated by Django 5.2.6 on 2025-09-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_chatmessage_chatroom_ecochallenge_ecopickupzone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('INR', 'Indian Rupee (₹)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('BRL', 'Brazilian Real (R$)'), ('MXN', 'Mexican Peso ($)')], default='USD', help_text='Currency for the price', max_length=3),
        ),
    ]
