# Generated by Django 5.2.6 on 2025-09-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image (required if no video provided)', null=True, upload_to='products/'),
        ),
    ]
