# Generated by Django 5.2.6 on 2025-09-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default_product.png', help_text='Product image (required)', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(default='products/videos/default_video.mp4', help_text='Product video (required)', upload_to='products/videos/'),
        ),
    ]
